// Seleecionamos la base de datos a utilizar.
use("ZOO");

// Insertamos varios documento en las colecciones seleccionadas (Poblamos la BBDD).

db.getCollection("Animales").insertMany([
  {
    Id_Animal: "BallH1",
    Especie: "Ballena gris",
    Nombre: "Eustaquia",
    Edad: 4,
    Pais_Origen: "Alaska",
  },
  {
    Id_Animal: "LeonM1",
    Especie: "León Asiático",
    Nombre: "Mufasa",
    Edad: 2,
    Pais_Origen: "India",
  },
  {
    Id_Animal: "BallM1",
    Especie: "Ballena gris",
    Nombre: "Messi",
    Edad: 5,
    Pais_Origen: "Alaska",
  },
  {
    Id_Animal: "LeonH1",
    Especie: "León Asiático",
    Nombre: "Palmera",
    Edad: 3,
    Pais_Origen: "India",
  },
  {
    Id_Animal: "JirafaM1",
    Especie: "Jirafa del sur",
    Nombre: "Melman",
    Edad: 10,
    Pais_Origen: "Kenia",
  },
  {
    Id_Animal: "JirafaH1",
    Especie: "Jirafa del sur",
    Nombre: "Sophie",
    Edad: 9,
    Pais_Origen: "Kenia",
  },
  {
    Id_Animal: "JirafaH2",
    Especie: "Jirafa del sur",
    Nombre: "Penny",
    Edad: 8,
    Pais_Origen: "Kenia",
  },
  {
    Id_Animal: "MonoM1",
    Especie: "Chimpancé",
    Nombre: "Amelio",
    Edad: 12,
    Pais_Origen: "África Central",
  },
  {
    Id_Animal: "ElefanteM1",
    Especie: "Elefante Africano",
    Nombre: "Dumbo",
    Edad: 25,
    Pais_Origen: "Kenia",
  },
  {
    Id_Animal: "LinceH1",
    Especie: "Lince Ibérico",
    Nombre: "Leo",
    Edad: 6,
    Pais_Origen: "España",
  },
  {
    Id_Animal: "OsoM1",
    Especie: "Oso Pardo",
    Nombre: "Winnie",
    Edad: 18,
    Pais_Origen: "Francia",
  },
  {
    Id_Animal: "OsoM2",
    Especie: "Oso Pardo",
    Nombre: "Yogi",
    Edad: 13,
    Pais_Origen: "Italia",
  },
  {
    Id_Animal: "ÁguilaM1",
    Especie: "Águila Real",
    Nombre: "Freedom",
    Edad: 4,
    Pais_Origen: "España",
  },
  {
    Id_Animal: "TigreM1",
    Especie: "Tigre de Bengala",
    Nombre: "Rex",
    Edad: 11,
    Pais_Origen: "India",
  },
  {
    Id_Animal: "CanguroH1",
    Especie: "Canguro Rojo",
    Nombre: "Skippy",
    Edad: 2,
    Pais_Origen: "Australia",
  },
  {
    Id_Animal: "SerpienteH1",
    Especie: "Cobra real",
    Nombre: "Kaa",
    Edad: 4,
    Pais_Origen: "India",
  },
  {
    Id_Animal: "GorilaM1",
    Especie: "Gorila de montaña",
    Nombre: "Koko",
    Edad: 12,
    Pais_Origen: "Ruanda",
  },
  {
    Id_Animal: "CebraH1",
    Especie: "Cebra de Burchell",
    Nombre: "Rayas",
    Edad: 5,
    Pais_Origen: "Sudáfrica",
  },
  {
    Id_Animal: "DelfínM1",
    Especie: "Delfín nariz de botella",
    Nombre: "Flipper",
    Edad: 8,
    Pais_Origen: "Estados Unidos",
  },
  {
    Id_Animal: "PingüinoH1",
    Especie: "Pingüino emperador",
    Nombre: "Tux",
    Edad: 3,
    Pais_Origen: "Antártida",
  },
  {
    Id_Animal: "RinoceronteM1",
    Especie: "Rinoceronte blanco",
    Nombre: "Toro",
    Edad: 9,
    Pais_Origen: "Sudáfrica",
  },
  {
    Id_Animal: "TortugaH1",
    Especie: "Tortuga marina",
    Nombre: "Shelly",
    Edad: 50,
    Pais_Origen: "Maldivas",
  },
  {
    Id_Animal: "LoboM1",
    Especie: "Lobo gris",
    Nombre: "Lupin",
    Edad: 6,
    Pais_Origen: "Estados Unidos",
  },
  {
    Id_Animal: "KoalaH1",
    Especie: "Koala",
    Nombre: "Milo",
    Edad: 4,
    Pais_Origen: "Australia",
  },
  {
    Id_Animal: "HipopótamoM1",
    Especie: "Hipopótamo común",
    Nombre: "Hugo",
    Edad: 12,
    Pais_Origen: "Kenia",
  },
  {
    Id_Animal: "FlamencoH1",
    Especie: "Flamenco rosado",
    Nombre: "Rosa",
    Edad: 8,
    Pais_Origen: "Bolivia",
  },
  {
    Id_Animal: "LémurM1",
    Especie: "Lémur de cola anillada",
    Nombre: "Leo",
    Edad: 5,
    Pais_Origen: "Madagascar",
  },
  {
    Id_Animal: "PumaH1",
    Especie: "Puma concolor",
    Nombre: "Luna",
    Edad: 7,
    Pais_Origen: "América",
  },
  {
    Id_Animal: "ZorroM1",
    Especie: "Zorro rojo",
    Nombre: "Foxy",
    Edad: 3,
    Pais_Origen: "América del Norte",
  },
  {
    Id_Animal: "GuepardoH1",
    Especie: "Guepardo",
    Nombre: "Cheetah",
    Edad: 4,
    Pais_Origen: "África",
  },
  {
    Id_Animal: "TucánM1",
    Especie: "Tucán toco",
    Nombre: "Tuki",
    Edad: 4,
    Pais_Origen: "América Central",
  },
  {
    Id_Animal: "ColibríH1",
    Especie: "Colibrí de garganta roja",
    Nombre: "Ruby",
    Edad: 2,
    Pais_Origen: "América del Norte",
  },
  {
    Id_Animal: "DelfínM2",
    Especie: "Delfín nariz de botella",
    Nombre: "Marina",
    Edad: 8,
    Pais_Origen: "Océano Atlántico",
  },
  {
    Id_Animal: "TortugaH2",
    Especie: "Tortuga verde",
    Nombre: "Shelly",
    Edad: 20,
    Pais_Origen: "Mar Caribe",
  },
  {
    Id_Animal: "ManatíM1",
    Especie: "Manatí antillano",
    Nombre: "Manny",
    Edad: 12,
    Pais_Origen: "Mar Caribe",
  },
  {
    Id_Animal: "NutriaM1",
    Especie: "Nutria de río",
    Nombre: "Oliver",
    Edad: 6,
    Pais_Origen: "Río Amazonas",
  },
  {
    Id_Animal: "FocaH1",
    Especie: "Foca común",
    Nombre: "Sandy",
    Edad: 10,
    Pais_Origen: "Océano Pacífico",
  },
  {
    Id_Animal: "CangrejoM1",
    Especie: "Cangrejo ermitaño",
    Nombre: "Claws",
    Edad: 3,
    Pais_Origen: "Océano Índico",
  },
  {
    Id_Animal: "PulpoH1",
    Especie: "Pulpo de anillos azules",
    Nombre: "Inky",
    Edad: 3,
    Pais_Origen: "Océano Índico",
  },
  {
    Id_Animal: "TiburónM1",
    Especie: "Tiburón blanco",
    Nombre: "Max",
    Edad: 15,
    Pais_Origen: "Océano Atlántico",
  },
  {
    Id_Animal: "PulpoH1",
    Especie: "Pulpo de anillos azules",
    Nombre: "Inky",
    Edad: 3,
    Pais_Origen: "Océano Índico",
  },
  {
    Id_Animal: "MedusaH1",
    Especie: "Medusa luna",
    Nombre: "Aqua",
    Edad: 2,
    Pais_Origen: "Océano Índico",
  },
  {
    Id_Animal: "PatoM1",
    Especie: "Pato mandarín",
    Nombre: "Quacky",
    Edad: 4,
    Pais_Origen: "Lagos de Asia",
  },
  {
    Id_Animal: "PezPayasoH1",
    Especie: "Pez payaso",
    Nombre: "Nemo",
    Edad: 1,
    Pais_Origen: "Arrecifes de coral",
  },
  {
    Id_Animal: "MantarrayaM1",
    Especie: "Mantarraya gigante",
    Nombre: "Rayo",
    Edad: 8,
    Pais_Origen: "Océano Pacífico",
  },
]);
